# Site settings
title: aconz2
email: username at gmail
description: > # this means to ignore newlines until "baseurl:"
  Stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aconz2.github.com" # the base hostname & protocol for your site
github_username:  aconz2

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
